backend:
  name: github
  branch: main
  repo: MikeNewXYZ/sveltia-cms-auth-hono
  base_url: http://localhost:3000
  auth_endpoint: api/auth

media_folder: sandbox/astro-cloudflare/src/assets/
public_folder: sandbox/astro-cloudflare/src/assets/

collections:
  - label: "Favourite Foods"
    name: "favouriteFoods"
    folder: "sandbox/astro-cloudflare/src/content/foods"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    format: json
    extension: json
    fields:
      - { label: "Image", name: "image", widget: "image", allow_multiple: false }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Rating", name: "rating", widget: "number", value_type: "int", min: 1, max: 10 }
