backend:
  name: github
  branch: main
  repo: MikeNewXYZ/sveltia-cms-auth-hono
  base_url: http://localhost:3000
  auth_endpoint: api/auth

media_folder: sandbox/nextjs-edge/src/assets/
public_folder: sandbox/nextjs-edge/src/assets/

collections:
  - label: Blogs
    name: blogs
    folder: sandbox/nextjs-edge/src/content/blogs
    create: true
    identifier_field: title
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
